<a href="https://colab.research.google.com/github/m-ritam/Python-Basics/blob/main/Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import numpy as np

arr=np.array([10,20,30,40,50,60])
#print("\n\n")
print(arr)
print(arr[0])
print("Type of array",type(arr))
print("Number of dimensions",arr.ndim)
print("shape of array",arr.shape)
print("size of array",arr.size)
print("data type of elements",arr.dtype)

[10 20 30 40 50 60]
10
Type of array <class 'numpy.ndarray'>
Number of dimensions 1
shape of array (6,)
size of array 6
data type of elements int64


In [6]:
for n in arr:
  print(n)

10
20
30
40
50
60


In [11]:
import numpy as np
i1=np.array([[7,4,29],
            [876,56,2],
            [37,38,4],
            [72,654320,946]])
print(i1)
print("Type of array",type(i1))
print("Number of dimensions",i1.ndim)
print("size of array",i1.size)
print("shape(row,column) of array",i1.shape)
print("data type of elements",i1.dtype)

[[     7      4     29]
 [   876     56      2]
 [    37     38      4]
 [    72 654320    946]]
Type of array <class 'numpy.ndarray'>
Number of dimensions 2
size of array 12
shape(row,column) of array (4, 3)
data type of elements int64


In [27]:
print(i1[0]) #first row
print(i1[:,0]) #first column

[ 7  4 29]
[  7 876  37  72]


In [31]:
import numpy as np

i23=np.array([10,20,30,40,50,60])
print(i23[0])

10


In [32]:
import numpy as np

arr=np.array([10,20,30,40,50,60])
print(i23[:])

[10 20 30 40 50 60]


In [33]:
import numpy as np

arr=np.array([10,20,30,40,50,60])
print(i23[2]+i23[3])

70


In [34]:
import numpy as np

arr=np.array([[10,20,30,40,50,60],[62,9,4,34,93,53]])
print(arr)
print(arr[1][3]) #2st row 4nd element

[[10 20 30 40 50 60]
 [62  9  4 34 93 53]]
34


In [35]:
#sum
import numpy as np

arr=np.array([[10,20,30,40,50,60],[70,90,40,50,90,80]])
print(arr)
print(np.sum(arr))

[[10 20 30 40 50 60]
 [70 90 40 50 90 80]]
630


In [36]:
#flatten
import numpy as np

arr=np.array([[10,20,30,40,50,60],[70,90,40,50,90,80]])
print(arr.flatten('F'))

[10 70 20 90 30 40 40 50 50 90 60 80]


In [37]:
#mix types
import numpy as np

i1 = np.array([
    [1, "apple"],
    [2, "banana"],
    [3, "cherry"]
])

print(i1)
print(type(i1[0, 0]), type(i1[0, 1]))  # Check types

[['1' 'apple']
 ['2' 'banana']
 ['3' 'cherry']]
<class 'numpy.str_'> <class 'numpy.str_'>
